### ISSUE TITLE
commonJS support missing

### ISSUE THREAD

**Issue by jutunen** [JoshK2/react-spinners-css#20]
Hello,
you might be aware that your spinners can't be directly used on node:

> import Circle from './Circle';
>^^^^^^
>
>SyntaxError: Cannot use import statement outside a module

Reference:
https://github.com/jaredpalmer/razzle/issues/1241

**Comment by JoshK2** [comment]
Thanks for opening the issue, I'll fix this as soon as possible.

**Comment by JoshK2** [comment]
@jutunen did you know what can be the solution to this problem?

**Comment by jutunen** [comment]
Well, I dunno, here is something: 
https://2ality.com/2019/10/hybrid-npm-packages.html
https://blog.logrocket.com/es-modules-in-node-js-12-from-experimental-to-release/
http://tobias-barth.net/blog/2019/11/How-to-bundle-your-library-and-why/

BTW, this issue does not concern Create React App, because it uses Babel to transpile the ESM modules to commonJS format, AFAIK:
https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs

**Comment by JoshK2** [comment]
> Well, I dunno, here is something:
> https://2ality.com/2019/10/hybrid-npm-packages.html
> https://blog.logrocket.com/es-modules-in-node-js-12-from-experimental-to-release/
> http://tobias-barth.net/blog/2019/11/How-to-bundle-your-library-and-why/
> 
> BTW, this issue does not concern Create React App, because it uses Babel to transpile the ESM modules to commonJS format, AFAIK:
> https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs

Thanks, how I can reproduce the error?

**Comment by jutunen** [comment]
> 
> Thanks, how I can reproduce the error?

Try to use your spinners on Razzle environment:
https://github.com/jaredpalmer/razzle

**Comment by JoshK2** [comment]
Hi, I fixed this in the last version.
And also wrote details about it here: https://github.com/JoshK2/react-spinners-css#how-to-use-with-ssr
