### ISSUE TITLE
Add types for Typescript

### ISSUE THREAD

**Issue by seisenreich** [JoshK2/react-spinners-css#22]
I tried to use this very promising looking spinner package in a typescript project.
And Typescript's linter told me that:

```
Could not find a declaration file for module 'react-spinners-css'. '/home/projec_path/node_modules/react-spinners-css/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-spinners-css` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-spinners-css';`ts(7016)
```

But there doesn't seem to be a `@types/react-spinners-css` package in the npm registry.
Will you add one, or can you tell me how I can make one by myself and publish it for others?
I never did that before, but I would tackle it after getting help about where to start :) 

Kind regards

**Comment by JoshK2** [comment]
Hi, thanks for opening the issue and for using this package.
I'll soon update this library to be in TS and it will include types.

At the moment, you can create a d.ts file in your project to avoid ts warning:
`react-spinners-css.d.ts`
and inside:
```
declare module 'react-spinners-css';
```

**Comment by seisenreich** [comment]
Hi Josh,

sounds fantastic. Thank you very much. I will try this trick out later.
Merry Christmas and have a nice day.

Regards

Josh Kuttler <notifications@github.com> schrieb am Do., 24. Dez. 2020,
14:45:

**Comment by JoshK2** [comment]
Hi, I published a new version with TypeScript support!!
https://www.npmjs.com/package/react-spinners-css

**Comment by husleuujii** [comment]
hello , i am getting UnhandledPromiseRejectionWarning: Unhandled promise rejection on typescript
